### PR TITLE
Source directory and Automated releases

### PR DESCRIPTION
**Pull request by S1M0N38**
I try to organize this git repo in a more structured way.

1.  I separate the latex files (put them all in **src folder**) from those used by github (*README*, *.gitignore*). Talking about Github  files the is also the need to choose a *LICENCE*. 

2. This separation also allows for a  **Continuous Integration** (CI) type of workflow. This means that when you push commits, Github server are configured to perform validation checks on *.tex* files and test if pdf can be successfully generated.

3. For an inexperience user tex could be hard so I setup a Github action that allow to automatically release a pdf version of the whole project when a tag commit is pushed. 

4. Finally, I update the *.gitognore* adding files that appear in my dev environment (obviously preserving the previous ones).

CI and Release process are based on a [template-repository](https://github.com/S1M0N38/latex-template) that I've recently created.

### CODE REVIEW

**Comment by ejuarezg** [comment]
How did you get the PDF to build correctly for your initial release? I'm encountering the following error. I think it has something to do with GITHUB_TOKEN permissions but I'm not sure.
build_error_2020-01-25

**Comment by S1M0N38** [comment]
The GITHUB_TOKEN should be created when a git action starts

 https://help.github.com/en/actions/automating-your-workflow-with-github-actions/authenticating-with-the-github_token

My github action  is a combination of two others:

- xu-cheng/latex-action@master
- actions/create-release@v1.0.0

The first one is used for pdf compilation, there shouldn't be no problem with that. 
The other was create by github him self and it's use for create a new release. 

I don't really know why such problem rises, the only thing that came I my mind is that repo is a cloned one and the issues can be related to that fact.

**Comment by ejuarezg** [comment]
I think you're right. The issue must have something to do with the fact that it is a forked repo. But, your newly created repo is also a forked repo so I'm confused. Thanks, anyway. I'll see if I can troubleshoot this later this week because the automatic building of the pdf is a neat feature.

**Comment by S1M0N38** [comment]
I try to run again the action on my forked repo and all goes well.

To make a release just use these commands (of course v0.1.2 it's the version number that you want to release while -m flag is the title of the release)
Screen Shot 2020-01-27 at 20 54 59

Another wired thing that I notice is that during the failed build the Generate workflow is run twice
Screen Shot 2020-01-27 at 20 53 39

Lastly check that the setting -> action is like 
Screen Shot 2020-01-27 at 21 02 00

**Comment by ejuarezg** [comment]
Thank you for your help! I was finally able to get it working. During my first attempt, I created the release through the GitHub website and the PDF failed to upload. This second attempt, I did it through the terminal and used your commands and the PDF was uploaded successfully.

The action permissions were also set correctly before so this was not the issue. I think the issue must be with the way GitHub handles releases when done through their website. From now on I'll be sticking to the terminal.

**Pull request merged**
